# Generated by Django 5.1.4 on 2024-12-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'permissions': [('can_add_reserva', 'Can add reserva'), ('can_delete_reserva', 'Can delete reserva'), ('can_change_reserva', 'Can change reserva'), ('can_view_reserva', 'Can view reserva')]},
        ),
    ]
